name: empty-spigot-plugin
version: @version@-@apiversion@
description: An empty example plugin for Spigot with Gradle
authors: [Rene Hollander]
website: https://github.com/ReneHollander/empty-spigot-plugin

main: com.example.emptyspigotplugin.EmptySpigotPlugin
